import { NextResponse } from "next/server"
import { dataFileExists, readData } from "@/lib/data-utils"

export async function GET() {
  try {
    const fileExists = await dataFileExists()
    let dataInfo = null

    if (fileExists) {
      try {
        const data = await readData()
        dataInfo = {
          version: data.metadata?.version || "unknown",
          lastUpdated: data.metadata?.lastUpdated || "unknown",
          totalRecords: data.metadata?.totalRecords || 0,
          autoGenerated: data.metadata?.autoGenerated || false,
          regions: Object.keys(data.regions || {}).length,
          species: (data.species || []).length,
        }
      } catch (error) {
        dataInfo = { error: "데이터 읽기 실패" }
      }
    }

    return NextResponse.json({
      success: true,
      status: "healthy",
      timestamp: new Date().toISOString(),
      dataFile: {
        exists: fileExists,
        path: "/data/microplastic-data.json",
        info: dataInfo,
      },
      system: {
        runtime: "Next.js API Routes",
        environment: process.env.NODE_ENV || "development",
        timestamp: new Date().toISOString(),
      },
    })
  } catch (error) {
    console.error("Health check 오류:", error)
    return NextResponse.json(
      {
        success: false,
        status: "unhealthy",
        error: "시스템 상태 확인 실패",
        timestamp: new Date().toISOString(),
      },
      { status: 500 },
    )
  }
}
